### Student Registration
POST http://localhost:5001/apis/student/register
Content-Type: application/json

{
    "userType": "student",
    "username": "student12",
    "email": "student12@gmail.com",
    "password": "password123",
    "skills": ["JavaScript", "React"],
    "education": ["BSc in Computer Science"],
    "projects": ["Project A", "Project B"]
}

### Student Login
POST http://localhost:5001/apis/student/login
Content-Type: application/json

{
    "email": "student12@gmail.com",
    "password": "password123"
}

### Company Registration
POST http://localhost:5001/apis/company/register
Content-Type: application/json

{
    "userType": "company",
    "email": "company@exampe.com",
    "password": "securepass@!23",
    "companyName": "Example Company",
    "location": "New York, USA",
    "description": "A tech company specializing in web development.",
    "website": "https://www.examplecompany.com"
}


### Company Login
POST http://localhost:5001/apis/company/login
Content-Type: application/json

{
    "email": "company@example.com",
    "password": "securepass@!23"
}

### Admin Registration
POST http://localhost:5001/apis/admin/register
Content-Type: application/json

{
    "userType": "admin",
    "email": "admin@example.com",
    "password": "adminPass123"
}

### Admin Login
POST http://localhost:5001/apis/admin/login
Content-Type: application/json

{
    "email": "admin@example.com",
    "password": "adminPass123"
}

### craete the job for students by the company
post http://localhost:5001/apis/job/create
Content-Type: application/json

 {


   "jobId": "fca30b31-35a3-4ebc-819b-254adc07fc62",
    "title": "Software Engineer",
   "companyName": "Example Company",
    "companyId": "COMP-1740835542137",
    "location": "india",
    "description": "Develop web applications using React and Node.js.",
    "skillsRequired": ["React", "Node.js"],
    "jobType": "Full-time",
    "experience": "2+ years",
    "salaryRange": "100000"

}
####applying for the job
POST http://localhost:5001/apis/job/apply
Content-Type: application/json

{
    "username": "student12",
    "jobId": "fca30b31-35a3-4ebc-819b-254adc07fc62",
    "resumeUrl": "https://drive.google.com/file/d/resume123/view"
}






### Create a Hackathon
POST http://localhost:5001/apis/hackathon/create
Content-Type: application/json

{
    "title": "AI Challenge",
    "problemStatement": "Build an AI model for image recognition.",
    "domain": "AI",
    "companyId": "60d21b4667d0d8992e610c85",
    "deadline": "2025-04-30",
    "hackathonId": "60d21b4667d0d8992e620c85"
}
### Participate in a Hackathon
PUT  http://localhost:5001/apis/hackathon/participate
Content-Type: application/json

{
    "username": "student",
    "hackathonId": "60d21b4667d0d8992e620c85",
    "gitRepository": "https://github.com/varunrevoori/HireSpace"
}


### Get All Hackathons
GET http://localhost:5001/apis/hackathon/all

### Get a Single Hackathon by ID
GET http://localhost:5001/apis/hackathon/60d21b4667d0d8992e610c85





### Submit Hackathon Solution
PUT  http://localhost:5001/apis/hackathon/submit
Content-Type: application/json

{
    "hackathonId": "60d21b4667d0d8992e620c85",
    "username": "student"
    
}





